const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "+94789200603"
const SESSION_ID = "PRABATH-MD~xvtDlaha#nc1y0jlutIcLrRY5F5HlyFM3ysXeVKyyAFGRtH6h78U"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
